-- Config OBS por club (técnico) + logs del puente + caminos para feedback de transmisión en overlay_state
-- club_id alineado con clubs.codigo (text), RLS con btrim()

CREATE TABLE IF NOT EXISTS public.club_obs_config (
    club_id text NOT NULL,
    obs_ws_password text NULL,
    obs_browser_source_name text NOT NULL DEFAULT 'Overlay DeCarambola',
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT club_obs_config_pkey PRIMARY KEY (club_id)
);

COMMENT ON TABLE public.club_obs_config IS 'Credenciales OBS por club; el bridge Node en el Mac del club lee esta fila (service role).';
COMMENT ON COLUMN public.club_obs_config.club_id IS 'clubs.codigo (mismo criterio que profiles.club_id en operación).';

CREATE TABLE IF NOT EXISTS public.obs_logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    club_id text NULL,
    match_id text NULL,
    level text NOT NULL DEFAULT 'error',
    message text NOT NULL,
    detail jsonb NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.obs_logs IS 'Errores del puente OBS; no afectan partida ni overlay.';

ALTER TABLE public.overlay_state ADD COLUMN IF NOT EXISTS club_id text NULL;
COMMENT ON COLUMN public.overlay_state.club_id IS 'clubs.codigo del club que publica; filtro del bridge.';

ALTER TABLE public.overlay_state ADD COLUMN IF NOT EXISTS stream_bridge_status text NULL;
COMMENT ON COLUMN public.overlay_state.stream_bridge_status IS 'pendiente | live | error_obs — escribe el bridge; TV lee para el botón.';

ALTER TABLE public.overlay_state ADD COLUMN IF NOT EXISTS stream_bridge_at timestamp with time zone NULL;

ALTER TABLE public.club_obs_config ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.obs_logs ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "club_obs_config_select_staff" ON public.club_obs_config;
CREATE POLICY "club_obs_config_select_staff"
    ON public.club_obs_config
    FOR SELECT
    TO authenticated
    USING (
        EXISTS (
            SELECT 1
            FROM public.profiles p
            WHERE p.id = auth.uid()
              AND (
                  p.role = 'superadmin'
                  OR (
                      btrim(p.club_id) = btrim(club_obs_config.club_id)
                      AND p.role IN ('club_admin', 'organizador')
                  )
              )
        )
    );

DROP POLICY IF EXISTS "club_obs_config_insert_staff" ON public.club_obs_config;
CREATE POLICY "club_obs_config_insert_staff"
    ON public.club_obs_config
    FOR INSERT
    TO authenticated
    WITH CHECK (
        EXISTS (
            SELECT 1
            FROM public.profiles p
            WHERE p.id = auth.uid()
              AND (
                  p.role = 'superadmin'
                  OR (
                      btrim(p.club_id) = btrim(club_obs_config.club_id)
                      AND p.role IN ('club_admin', 'organizador')
                  )
              )
        )
    );

DROP POLICY IF EXISTS "club_obs_config_update_staff" ON public.club_obs_config;
CREATE POLICY "club_obs_config_update_staff"
    ON public.club_obs_config
    FOR UPDATE
    TO authenticated
    USING (
        EXISTS (
            SELECT 1
            FROM public.profiles p
            WHERE p.id = auth.uid()
              AND (
                  p.role = 'superadmin'
                  OR (
                      btrim(p.club_id) = btrim(club_obs_config.club_id)
                      AND p.role IN ('club_admin', 'organizador')
                  )
              )
        )
    )
    WITH CHECK (
        EXISTS (
            SELECT 1
            FROM public.profiles p
            WHERE p.id = auth.uid()
              AND (
                  p.role = 'superadmin'
                  OR (
                      btrim(p.club_id) = btrim(club_obs_config.club_id)
                      AND p.role IN ('club_admin', 'organizador')
                  )
              )
        )
    );

-- Logs: solo inserción por service_role (sin policy = deny authenticated); lectura opcional superadmin si se agrega después
DROP POLICY IF EXISTS "obs_logs_no_client" ON public.obs_logs;
CREATE POLICY "obs_logs_no_client"
    ON public.obs_logs
    FOR ALL
    TO authenticated
    USING (false)
    WITH CHECK (false);

-- Realtime: overlay_state para el puente y la TV (idempotente si ya estaba)
DO $migration$
BEGIN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.overlay_state;
EXCEPTION
    WHEN duplicate_object THEN
        NULL;
END $migration$;
